//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviewData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ID { get; set; }
        public int RestID { get; set; }
        public string Reviewer { get; set; }
        public string Text { get; set; }
        public double Rating { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
